spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/srb_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&autoReconnectForPools=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: qwe123
    # 下面为连接池的补充设置，应用到上面所有数据源中# 初始化大小，最小，最大
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

  # redis配置
  redis:
    host: 192.168.159.131
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20  # 最大连接数,负值表示没有限制,默认8
        max-wait: -1    # 最大阻塞等待时间,负值表示没限制,默认-1
        max-idle: 8     # 最大空闲连接，默认8
        min-idle: 0     # 最小空闲连接，默认0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*
  global-config:
    db-config:
      id-type: AUTO

knife4j:
  basic:
    enable: true

